// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eklucbgzzluxntmijrtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbHVjYmd6emx1eG50bWlqcnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTYzNDUsImV4cCI6MjA2NDczMjM0NX0.uq6wFuyvibyEuy-u3bq1FNdt0FKcxYXNrtgwjg5L_LA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);